name: Tag and Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  bump-version-and-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.3'

      - name: Bump version
        run: |
          CURRENT_VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
          VERSION_NAME=$(echo $CURRENT_VERSION | cut -d'+' -f1)
          BUILD_NUMBER=$(echo $CURRENT_VERSION | cut -d'+' -f2 || echo 0)
          NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          NEW_VERSION="$VERSION_NAME+$NEW_BUILD_NUMBER"
          sed -i "s/version: .*/version: $NEW_VERSION/" pubspec.yaml
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and push version bump
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add pubspec.yaml
          git commit -m "Bump version to $NEW_VERSION"
          git push

      - name: Create and push tag
        run: |
          TAG_NAME="v${NEW_VERSION%%+*}"
          git tag "$TAG_NAME"
          git push origin "$TAG_NAME"
