name: Deploy to pub.dev

on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write # Required for OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Increment version
        run: |
          CURRENT_VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
          VERSION_NAME=$(echo $CURRENT_VERSION | cut -d'+' -f1)
          BUILD_NUMBER=$(echo $CURRENT_VERSION | cut -d'+' -f2 || echo 0)
          NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          NEW_VERSION="$VERSION_NAME+$NEW_BUILD_NUMBER"
          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" pubspec.yaml
          echo "Updated version to $NEW_VERSION"

      - name: Commit version increment
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add pubspec.yaml
          git commit -m "Bump version to $NEW_VERSION"
          git push

      - name: Publish to pub.dev
        run: dart pub publish --force