name: Deploy to pub.dev

on:
  push:
    branches:
      - master

permissions:
  contents: write
  id-token: write # Required for OIDC authentication

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.x' # Updated to support Dart 3.5.0+

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: |
          flutter pub get || (echo "Failed to get dependencies: $?" && exit 1)

      - name: Increment version
        run: |
          CURRENT_VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
          VERSION_NAME=$(echo $CURRENT_VERSION | cut -d'+' -f1)
          BUILD_NUMBER=$(echo $CURRENT_VERSION | cut -d'+' -f2 || echo 0)
          NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          NEW_VERSION="$VERSION_NAME+$NEW_BUILD_NUMBER"
          sed -i "s/version: $CURRENT_VERSION/version: $NEW_VERSION/" pubspec.yaml
          echo "Updated version to $NEW_VERSION"

      - name: Commit version increment
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add pubspec.yaml
          git commit -m "Bump version to $NEW_VERSION"
          git push

      - name: Publish to pub.dev
        run: flutter pub publish --force