name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read
  id-token: write  # Required for OIDC auth

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
